{-# OPTIONS_GHC -Wno-unrecognised-pragmas #-}
{-# HLINT ignore "Use camelCase" #-}
module Editor.Select where
import Editor.Cursor
import Editor.Typesetting
import Other.Error
import Type
import qualified Data.Sequence as DS
import qualified Foreign.C.Types as FCT
import qualified GHC.Stack as GS

start_select::GS.HasCallStack=>DS.Seq (DS.Seq (Char,Int,FCT.CInt),Int,Int,Bool)->Typesetting->Int->Int
start_select DS.Empty _ _=error "start_select: error 1"
start_select ((_,number,_,_) DS.:<| _) typesetting block_number=typesetting_left typesetting number block_number

end_select::GS.HasCallStack=>DS.Seq (DS.Seq (Char,Int,FCT.CInt),Int,Int,Bool)->Typesetting->Int->(Int,Int)
end_select DS.Empty _ _=error "end_select: error 1"
end_select (_ DS.:|> (_,number,char_number,_)) typesetting block_number=(typesetting_right typesetting number block_number,char_number)

min_select_all::DS.Seq (DS.Seq (Char,Int,FCT.CInt),Int,Int,Bool)->Typesetting->Int->Int->Cursor->Maybe Cursor
min_select_all _ _ _ _ Cursor_none=Nothing
min_select_all seq_seq_char typesetting block_number max_row (Cursor_single cursor_press _ _ _ _)=let number_block_start=start_select seq_seq_char typesetting block_number in let (number_block_end,number_char_end)=end_select seq_seq_char typesetting block_number in if max_row==0&&number_char_end==0 then Nothing else Just (Cursor_double cursor_press True 0 number_block_start 0 number_block_start max_row number_block_end number_char_end number_block_end)
min_select_all seq_seq_char typesetting block_number max_row (Cursor_double cursor_press cursor_where cursor_row_start _ cursor_char_start _ cursor_row_end _ cursor_char_end _)=let number_block_start=start_select seq_seq_char typesetting block_number in let (number_block_end,number_char_end)=end_select seq_seq_char typesetting block_number in if cursor_where&&cursor_row_start==0&&cursor_char_start==number_block_start&&cursor_row_end==max_row&&cursor_char_end==number_block_end then Nothing else Just (Cursor_double cursor_press True 0 number_block_start 0 number_block_start max_row number_block_end number_char_end number_block_end)

max_select_all::DS.Seq (DS.Seq (Char,Int,FCT.CInt),Int,Int,Bool)->Typesetting->Int->Int->Cursor->Maybe Cursor
max_select_all _ _ _ _ Cursor_none=Nothing
max_select_all seq_seq_char typesetting block_number max_row (Cursor_single cursor_press _ _ _ _)=let number_block_start=start_select seq_seq_char typesetting block_number in let (number_block_end,number_char_end)=end_select seq_seq_char typesetting block_number in if max_row==0&&number_char_end==0 then Nothing else Just (Cursor_double cursor_press False 0 number_block_start 0 number_block_start max_row number_block_end number_char_end number_block_end)
max_select_all seq_seq_char typesetting block_number max_row (Cursor_double cursor_press cursor_where cursor_row_start _ cursor_char_start _ cursor_row_end _ cursor_char_end _)=let number_block_start=start_select seq_seq_char typesetting block_number in let (number_block_end,number_char_end)=end_select seq_seq_char typesetting block_number in if not cursor_where&&cursor_row_start==0&&cursor_char_start==number_block_start&&cursor_row_end==max_row&&cursor_char_end==number_block_end then Nothing else Just (Cursor_double cursor_press False 0 number_block_start 0 number_block_start max_row number_block_end number_char_end number_block_end)

select_start::DS.Seq (DS.Seq (Char,Int,FCT.CInt),Int,Int,Bool)->Typesetting->Int->Cursor->Maybe Cursor
select_start _ _ _ Cursor_none=Nothing
select_start seq_seq_char typesetting block_number (Cursor_single cursor_press cursor_row cursor_block cursor_char cursor_click)=let number_block=start_select seq_seq_char typesetting block_number in if cursor_row==0&&cursor_char==0 then Nothing else Just (Cursor_double cursor_press True 0 number_block 0 number_block cursor_row cursor_block cursor_char cursor_click)
select_start seq_seq_char typesetting block_number (Cursor_double cursor_press cursor_where cursor_row_start cursor_block_start cursor_char_start cursor_click_start cursor_row_end cursor_block_end cursor_char_end cursor_click_end)=let number_block=start_select seq_seq_char typesetting block_number in if cursor_where then if cursor_row_start==0&&cursor_char_start==0 then Nothing else Just (Cursor_double cursor_press True 0 number_block 0 number_block cursor_row_end cursor_block_end cursor_char_end cursor_click_end) else Just (Cursor_double cursor_press True 0 number_block 0 number_block cursor_row_start cursor_block_start cursor_char_start cursor_click_start)

select_end::DS.Seq (DS.Seq (Char,Int,FCT.CInt),Int,Int,Bool)->Typesetting->Int->Int->Cursor->Maybe Cursor
select_end _ _ _ _ Cursor_none=Nothing
select_end seq_seq_char typesetting block_number max_row (Cursor_single cursor_press cursor_row cursor_block cursor_char cursor_click)=let (number_block,number_char)=end_select seq_seq_char typesetting block_number in if cursor_row==max_row&&cursor_char==number_char then Nothing else Just (Cursor_double cursor_press False cursor_row cursor_block cursor_char cursor_click max_row number_block number_char number_block)
select_end seq_seq_char typesetting block_number max_row (Cursor_double cursor_press cursor_where cursor_row_start cursor_block_start cursor_char_start cursor_click_start cursor_row_end cursor_block_end cursor_char_end cursor_click_end)=let (number_block,number_char)=end_select seq_seq_char typesetting block_number in if cursor_where then Just (Cursor_double cursor_press False cursor_row_end cursor_block_end cursor_char_end cursor_click_end max_row number_block number_char number_block) else if cursor_row_end==max_row&&cursor_char_end==number_char then Nothing else Just (Cursor_double cursor_press False cursor_row_start cursor_block_start cursor_char_start cursor_click_start max_row number_block number_char number_block)

start_select_paragraph::DS.Seq (DS.Seq (Char,Int,FCT.CInt),Int,Int,Bool)->Typesetting->Int->Int->(Int,Int)
start_select_paragraph seq_seq_char typesetting block_number row=case error_lookup_sequence "start_select_paragraph: error 1" row seq_seq_char of
    (_,number,_,_)->let (new_row,new_number)=find_paragraph_min (DS.take row seq_seq_char) row number in (new_row,typesetting_left typesetting new_number block_number)

end_select_paragraph::DS.Seq (DS.Seq (Char,Int,FCT.CInt),Int,Int,Bool)->Typesetting->Int->Int->(Int,Int,Int)
end_select_paragraph seq_seq_char typesetting block_number row=case error_lookup_sequence "end_select_paragraph: error 1" row seq_seq_char of
    (_,number,char_number,end)->if end then (row,number,char_number) else let (new_row,new_number,new_char_number)=find_paragraph_max (DS.drop (row+1) seq_seq_char) row in (new_row,typesetting_right typesetting new_number block_number,new_char_number)

min_select_paragraph_all::DS.Seq (DS.Seq (Char,Int,FCT.CInt),Int,Int,Bool)->Typesetting->Int->Cursor->Maybe (Int,Maybe Cursor)
min_select_paragraph_all _ _ _ Cursor_none=Nothing
min_select_paragraph_all seq_seq_char typesetting block_number (Cursor_single cursor_press cursor_row _ _ _)=let (row_start,number_block_start)=start_select_paragraph seq_seq_char typesetting block_number cursor_row in let (row_end,number_block_end,number_char_end)=end_select_paragraph seq_seq_char typesetting block_number cursor_row in if row_start==row_end&&number_char_end==0 then Just (row_start,Nothing) else Just (row_start,Just (Cursor_double cursor_press True row_start number_block_start 0 number_block_start row_end number_block_end number_char_end number_block_end))
min_select_paragraph_all seq_seq_char typesetting block_number (Cursor_double cursor_press cursor_where cursor_row_start _ cursor_char_start _ cursor_row_end _ cursor_char_end _)=let row=if cursor_where then cursor_row_start else cursor_row_end in let (row_start,number_block_start)=start_select_paragraph seq_seq_char typesetting block_number row in let (row_end,number_block_end,number_char_end)=end_select_paragraph seq_seq_char typesetting block_number row in if cursor_where&&cursor_row_start==row_start&&cursor_char_start==0&&cursor_row_end==row_end&&cursor_char_end==number_char_end then Just (row_start,Nothing) else Just (row_start,Just (Cursor_double cursor_press True row_start number_block_start 0 number_block_start row_end number_block_end number_char_end number_block_end))

max_select_paragraph_all::DS.Seq (DS.Seq (Char,Int,FCT.CInt),Int,Int,Bool)->Typesetting->Int->Cursor->Maybe (Int,Maybe Cursor)
max_select_paragraph_all _ _ _ Cursor_none=Nothing
max_select_paragraph_all seq_seq_char typesetting block_number (Cursor_single cursor_press cursor_row _ _ _)=let (row_start,number_block_start)=start_select_paragraph seq_seq_char typesetting block_number cursor_row in let (row_end,number_block_end,number_char_end)=end_select_paragraph seq_seq_char typesetting block_number cursor_row in if row_start==row_end&&number_char_end==0 then Just (row_end,Nothing) else Just (row_end,Just (Cursor_double cursor_press False row_start number_block_start 0 number_block_start row_end number_block_end number_char_end number_block_end))
max_select_paragraph_all seq_seq_char typesetting block_number (Cursor_double cursor_press cursor_where cursor_row_start _ cursor_char_start _ cursor_row_end _ cursor_char_end _)=let row=if cursor_where then cursor_row_start else cursor_row_end in let (row_start,number_block_start)=start_select_paragraph seq_seq_char typesetting block_number row in let (row_end,number_block_end,number_char_end)=end_select_paragraph seq_seq_char typesetting block_number row in if not cursor_where&&cursor_row_start==row_start&&cursor_char_start==0&&cursor_row_end==row_end&&cursor_char_end==number_char_end then Just (row_end,Nothing) else Just (row_end,Just (Cursor_double cursor_press False row_start number_block_start 0 number_block_start row_end number_block_end number_char_end number_block_end))

select_paragraph_start::DS.Seq (DS.Seq (Char,Int,FCT.CInt),Int,Int,Bool)->Typesetting->Int->Cursor->Maybe (Int,Maybe Cursor)
select_paragraph_start _ _ _ Cursor_none=Nothing
select_paragraph_start seq_seq_char typesetting block_number (Cursor_single cursor_press cursor_row cursor_block cursor_char cursor_click)=let (row,number_block)=start_select_paragraph seq_seq_char typesetting block_number cursor_row in if cursor_row==row&&cursor_char==0 then Just (row,Nothing) else Just (row,Just (Cursor_double cursor_press True row number_block 0 number_block cursor_row cursor_block cursor_char cursor_click))
select_paragraph_start seq_seq_char typesetting block_number (Cursor_double cursor_press cursor_where cursor_row_start cursor_block_start cursor_char_start cursor_click_start cursor_row_end cursor_block_end cursor_char_end cursor_click_end)=if cursor_where then let (row,number_block)=start_select_paragraph seq_seq_char typesetting block_number cursor_row_start in if cursor_row_start==row&&cursor_char_start==0 then Just (row,Nothing) else Just (row,Just (Cursor_double cursor_press True row number_block 0 number_block cursor_row_end cursor_block_end cursor_char_end cursor_click_end)) else let (row,number_block)=start_select_paragraph seq_seq_char typesetting block_number cursor_row_end in if cursor_row_end==row&&cursor_char_end==0 then Just (row,Nothing) else if (row,0)<(cursor_row_start,cursor_char_start) then Just (row,Just (Cursor_double cursor_press True row number_block 0 number_block cursor_row_start cursor_block_start cursor_char_start cursor_click_start)) else Just (row,Just (Cursor_double cursor_press False cursor_row_start cursor_block_start cursor_char_start cursor_click_start row number_block 0 number_block))

select_paragraph_end::DS.Seq (DS.Seq (Char,Int,FCT.CInt),Int,Int,Bool)->Typesetting->Int->Cursor->Maybe (Int,Maybe Cursor)
select_paragraph_end _ _ _ Cursor_none=Nothing
select_paragraph_end seq_seq_char typesetting block_number (Cursor_single cursor_press cursor_row cursor_block cursor_char cursor_click)=let (row,number_block,number_char)=end_select_paragraph seq_seq_char typesetting block_number cursor_row in if cursor_row==row&&cursor_char==number_char then Just (row,Nothing) else Just (row,Just (Cursor_double cursor_press False cursor_row cursor_block cursor_char cursor_click row number_block number_char number_block))
select_paragraph_end seq_seq_char typesetting block_number (Cursor_double cursor_press cursor_where cursor_row_start cursor_block_start cursor_char_start cursor_click_start cursor_row_end cursor_block_end cursor_char_end cursor_click_end)=if cursor_where then let (row,number_block,number_char)=end_select_paragraph seq_seq_char typesetting block_number cursor_row_start in if cursor_row_start==row&&cursor_char_start==number_char then Just (row,Nothing) else if (cursor_row_end,cursor_char_end)<(row,number_char) then Just (row,Just (Cursor_double cursor_press False cursor_row_end cursor_block_end cursor_char_end cursor_click_end row number_block number_char number_block)) else Just (row,Just (Cursor_double cursor_press True row number_block number_char number_block cursor_row_end cursor_block_end cursor_char_end cursor_click_end)) else let (row,number_block,number_char)=end_select_paragraph seq_seq_char typesetting block_number cursor_row_end in if cursor_row_end==row&&cursor_char_end==number_char then Just (row,Nothing) else Just (row,Just (Cursor_double cursor_press False cursor_row_start cursor_block_start cursor_char_start cursor_click_start row number_block number_char number_block))

select_row::DS.Seq (DS.Seq (Char,Int,FCT.CInt),Int,Int,Bool)->Typesetting->Int->Int->(Int,Int,Int)
select_row seq_seq_char typesetting block_number row=case error_lookup_sequence "select_row: error 1" row seq_seq_char of
    (_,number,char_number,_)->(typesetting_left typesetting number block_number,typesetting_right typesetting number block_number,char_number)

start_select_row::DS.Seq (DS.Seq (Char,Int,FCT.CInt),Int,Int,Bool)->Typesetting->Int->Int->Int
start_select_row seq_seq_char typesetting block_number row=case error_lookup_sequence "start_select_row: error 1" row seq_seq_char of
    (_,number,_,_)->typesetting_left typesetting number block_number

end_select_row::DS.Seq (DS.Seq (Char,Int,FCT.CInt),Int,Int,Bool)->Typesetting->Int->Int->(Int,Int)
end_select_row seq_seq_char typesetting block_number row=case error_lookup_sequence "end_select_row: error 1" row seq_seq_char of
    (_,number,char_number,_)->(typesetting_right typesetting number block_number,char_number)

min_select_row_all::DS.Seq (DS.Seq (Char,Int,FCT.CInt),Int,Int,Bool)->Typesetting->Int->Cursor->Maybe (Int,Maybe Cursor)
min_select_row_all _ _ _ Cursor_none=Nothing
min_select_row_all seq_seq_char typesetting block_number (Cursor_single cursor_press cursor_row _ _ _)=let (number_block_start,number_block_end,number_char_end)=select_row seq_seq_char typesetting block_number cursor_row in if number_char_end==0 then Just (cursor_row,Nothing) else Just (cursor_row,Just (Cursor_double cursor_press True cursor_row number_block_start 0 number_block_start cursor_row number_block_end number_char_end number_block_end))
min_select_row_all seq_seq_char typesetting block_number (Cursor_double cursor_press cursor_where cursor_row_start _ cursor_char_start _ cursor_row_end _ cursor_char_end _)=if cursor_where then let (number_block_start,number_block_end,number_char_end)=select_row seq_seq_char typesetting block_number cursor_row_start in if cursor_char_start==0&&cursor_row_end==cursor_row_start&&cursor_char_end==number_char_end then Just (cursor_row_start,Nothing) else Just (cursor_row_start,Just (Cursor_double cursor_press True cursor_row_start number_block_start 0 number_block_start cursor_row_start number_block_end number_char_end number_block_end)) else let (number_block_start,number_block_end,number_char_end)=select_row seq_seq_char typesetting block_number cursor_row_end in Just (cursor_row_end,Just (Cursor_double cursor_press True cursor_row_end number_block_start 0 number_block_start cursor_row_end number_block_end number_char_end number_block_end))

max_select_row_all::DS.Seq (DS.Seq (Char,Int,FCT.CInt),Int,Int,Bool)->Typesetting->Int->Cursor->Maybe (Int,Maybe Cursor)
max_select_row_all _ _ _ Cursor_none=Nothing
max_select_row_all seq_seq_char typesetting block_number (Cursor_single cursor_press cursor_row _ _ _)=let (number_block_start,number_block_end,number_char_end)=select_row seq_seq_char typesetting block_number cursor_row in if number_char_end==0 then Just (cursor_row,Nothing) else Just (cursor_row,Just (Cursor_double cursor_press False cursor_row number_block_start 0 number_block_start cursor_row number_block_end number_char_end number_block_end))
max_select_row_all seq_seq_char typesetting block_number (Cursor_double cursor_press cursor_where cursor_row_start _ cursor_char_start _ cursor_row_end _ cursor_char_end _)=if cursor_where then let (number_block_start,number_block_end,number_char_end)=select_row seq_seq_char typesetting block_number cursor_row_start in Just (cursor_row_start,Just (Cursor_double cursor_press False cursor_row_start number_block_start 0 number_block_start cursor_row_start number_block_end number_char_end number_block_end)) else let (number_block_start,number_block_end,number_char_end)=select_row seq_seq_char typesetting block_number cursor_row_end in if cursor_row_start==cursor_row_end&&cursor_char_start==0&&cursor_char_end==number_char_end then Just (cursor_row_end,Nothing) else Just (cursor_row_end,Just (Cursor_double cursor_press False cursor_row_end number_block_start 0 number_block_start cursor_row_end number_block_end number_char_end number_block_end))

select_row_start::DS.Seq (DS.Seq (Char,Int,FCT.CInt),Int,Int,Bool)->Typesetting->Int->Cursor->Maybe (Int,Maybe Cursor)
select_row_start _ _ _ Cursor_none=Nothing
select_row_start seq_seq_char typesetting block_number (Cursor_single cursor_press cursor_row cursor_block cursor_char cursor_click)=let number_block=start_select_row seq_seq_char typesetting block_number cursor_row in if cursor_char==0 then Just (cursor_row,Nothing) else Just (cursor_row,Just (Cursor_double cursor_press True cursor_row number_block 0 number_block cursor_row cursor_block cursor_char cursor_click))
select_row_start seq_seq_char typesetting block_number (Cursor_double cursor_press cursor_where cursor_row_start cursor_block_start cursor_char_start cursor_click_start cursor_row_end cursor_block_end cursor_char_end cursor_click_end)=if cursor_where then let number_block=start_select_row seq_seq_char typesetting block_number cursor_row_start in if cursor_char_start==0 then Just (cursor_row_start,Nothing) else Just (cursor_row_start,Just (Cursor_double cursor_press True cursor_row_start number_block 0 number_block cursor_row_end cursor_block_end cursor_char_end cursor_click_end)) else let number_block=start_select_row seq_seq_char typesetting block_number cursor_row_end in if cursor_char_end==0 then Just (cursor_row_end,Nothing) else if (cursor_row_end,0)<(cursor_row_start,cursor_char_start) then Just (cursor_row_end,Just (Cursor_double cursor_press True cursor_row_end number_block 0 number_block cursor_row_start cursor_block_start cursor_char_start cursor_click_start)) else Just (cursor_row_end,Just (Cursor_double cursor_press False cursor_row_start cursor_block_start cursor_char_start cursor_click_start cursor_row_end number_block 0 number_block))

select_row_end::DS.Seq (DS.Seq (Char,Int,FCT.CInt),Int,Int,Bool)->Typesetting->Int->Cursor->Maybe (Int,Maybe Cursor)
select_row_end _ _ _ Cursor_none=Nothing
select_row_end seq_seq_char typesetting block_number (Cursor_single cursor_press cursor_row cursor_block cursor_char cursor_click)=let (number_block,number_char)=end_select_row seq_seq_char typesetting block_number cursor_row in if cursor_char==number_char then Just (cursor_row,Nothing) else Just (cursor_row,Just (Cursor_double cursor_press False cursor_row cursor_block cursor_char cursor_click cursor_row number_block number_char number_block))
select_row_end seq_seq_char typesetting block_number (Cursor_double cursor_press cursor_where cursor_row_start cursor_block_start cursor_char_start cursor_click_start cursor_row_end cursor_block_end cursor_char_end cursor_click_end)=if cursor_where then let (number_block,number_char)=end_select_row seq_seq_char typesetting block_number cursor_row_start in if cursor_char_start==number_char then Just (cursor_row_start,Nothing) else if (cursor_row_end,cursor_char_end)<(cursor_row_start,number_char) then Just (cursor_row_start,Just (Cursor_double cursor_press False cursor_row_end cursor_block_end cursor_char_end cursor_click_end cursor_row_start number_block number_char number_block)) else Just (cursor_row_start,Just (Cursor_double cursor_press True cursor_row_start number_block number_char number_block cursor_row_end cursor_block_end cursor_char_end cursor_click_end)) else let (number_block,number_char)=end_select_row seq_seq_char typesetting block_number cursor_row_end in if cursor_char_end==number_char then Just (cursor_row_end,Nothing) else Just (cursor_row_end,Just (Cursor_double cursor_press False cursor_row_start cursor_block_start cursor_char_start cursor_click_start cursor_row_end number_block number_char number_block))

left_select::DS.Seq (DS.Seq (Char,Int,FCT.CInt),Int,Int,Bool)->Int->Int->Int->Int
left_select seq_seq_char cursor_row cursor_block cursor_char=case error_lookup_sequence "left_select: error 1" cursor_row seq_seq_char of
    (seq_char,_,_,_)->case error_lookup_sequence "left_select: error 2" cursor_char seq_char of
        (_,block,_)->cursor_block-block

left_select_start::DS.Seq (DS.Seq (Char,Int,FCT.CInt),Int,Int,Bool)->Typesetting->Int->Int->(Int,Int)
left_select_start seq_seq_char typesetting block_number cursor_row=case error_lookup_sequence "left_select_start: error 1" cursor_row seq_seq_char of
    (_,number,char_number,_)->(typesetting_right typesetting number block_number,char_number)

select_left::DS.Seq (DS.Seq (Char,Int,FCT.CInt),Int,Int,Bool)->Typesetting->Int->Cursor->Maybe (Int,Maybe Cursor)
select_left _ _ _ Cursor_none=Nothing
select_left seq_seq_char typesetting block_number (Cursor_single cursor_press cursor_row cursor_block cursor_char cursor_click)
    |cursor_row==0=if cursor_char==0 then Just (0,Nothing) else let new_cursor_char=cursor_char-1 in let new_cursor_block=left_select seq_seq_char 0 cursor_block new_cursor_char in Just (0,Just (Cursor_double cursor_press True 0 new_cursor_block new_cursor_char new_cursor_block 0 cursor_block cursor_char cursor_click))
    |otherwise=if cursor_char==0 then let new_cursor_row=cursor_row-1 in let (new_cursor_block,new_cursor_char)=left_select_start seq_seq_char typesetting block_number new_cursor_row in Just (new_cursor_row,Just (Cursor_double cursor_press True new_cursor_row new_cursor_block new_cursor_char new_cursor_block cursor_row cursor_block 0 cursor_click)) else let new_cursor_char=cursor_char-1 in let new_cursor_block=left_select seq_seq_char cursor_row cursor_block new_cursor_char in Just (cursor_row,Just (Cursor_double cursor_press True cursor_row new_cursor_block new_cursor_char new_cursor_block cursor_row cursor_block cursor_char cursor_click))
select_left seq_seq_char typesetting block_number (Cursor_double cursor_press cursor_where cursor_row_start cursor_block_start cursor_char_start cursor_click_start cursor_row_end cursor_block_end cursor_char_end cursor_click_end)
    |cursor_where=if cursor_row_start==0 then if cursor_char_start==0 then Just (0,Nothing) else let new_cursor_char=cursor_char_start-1 in let new_cursor_block=left_select seq_seq_char 0 cursor_block_start new_cursor_char in Just (0,Just (Cursor_double cursor_press True 0 new_cursor_block new_cursor_char new_cursor_block cursor_row_end cursor_block_end cursor_char_end cursor_click_end)) else if cursor_char_start==0 then let new_cursor_row=cursor_row_start-1 in let (new_cursor_block,new_cursor_char)=left_select_start seq_seq_char typesetting block_number new_cursor_row in Just (new_cursor_row,Just (Cursor_double cursor_press True new_cursor_row new_cursor_block new_cursor_char new_cursor_block cursor_row_end cursor_block_end cursor_char_end cursor_click_end)) else let new_cursor_char=cursor_char_start-1 in let new_cursor_block=left_select seq_seq_char cursor_row_start cursor_block_start new_cursor_char in Just (cursor_row_start,Just (Cursor_double cursor_press True cursor_row_start new_cursor_block new_cursor_char new_cursor_block cursor_row_end cursor_block_end cursor_char_end cursor_click_end))
    |otherwise=if cursor_row_end==0 then if cursor_char_start+1==cursor_char_end then Just (0,Just (Cursor_single cursor_press 0 cursor_block_start cursor_char_start cursor_click_start)) else let new_cursor_char=cursor_char_end-1 in let new_cursor_block=left_select seq_seq_char 0 cursor_block_end new_cursor_char in Just (0,Just (Cursor_double cursor_press False 0 cursor_block_start cursor_char_start cursor_click_start 0 new_cursor_block new_cursor_char new_cursor_block)) else if cursor_char_end==0 then let new_cursor_row=cursor_row_end-1 in let (new_cursor_block,new_cursor_char)=left_select_start seq_seq_char typesetting block_number new_cursor_row in if cursor_row_start==new_cursor_row&&cursor_char_start==new_cursor_char then Just (cursor_row_start,Just (Cursor_single cursor_press cursor_row_start cursor_block_start cursor_char_start cursor_click_start)) else Just (new_cursor_row,Just (Cursor_double cursor_press False cursor_row_start cursor_block_start cursor_char_start cursor_click_start new_cursor_row new_cursor_block new_cursor_char new_cursor_block)) else if cursor_row_start==cursor_row_end&&cursor_char_start+1==cursor_char_end then Just (cursor_row_start,Just (Cursor_single cursor_press cursor_row_start cursor_block_start cursor_char_start cursor_click_start)) else let new_cursor_char=cursor_char_end-1 in let new_cursor_block=left_select seq_seq_char cursor_row_end cursor_block_end new_cursor_char in Just (cursor_row_end,Just (Cursor_double cursor_press False cursor_row_start cursor_block_start cursor_char_start cursor_click_start cursor_row_end new_cursor_block new_cursor_char new_cursor_block))

right_select::DS.Seq (Char,Int,FCT.CInt)->Int->Int->Int
right_select seq_char cursor_block cursor_char=case error_lookup_sequence "right_select: error 1" cursor_char seq_char of
    (_,block,_)->cursor_block+block

right_select_end::DS.Seq (DS.Seq (Char,Int,FCT.CInt),Int,Int,Bool)->Typesetting->Int->Int->Int
right_select_end seq_seq_char typesetting block_number cursor_row=case error_lookup_sequence "right_select_end: error 1" cursor_row seq_seq_char of
    (_,number,_,_)->typesetting_left typesetting number block_number

select_right::DS.Seq (DS.Seq (Char,Int,FCT.CInt),Int,Int,Bool)->Typesetting->Int->Int->Cursor->Maybe (Int,Maybe Cursor)
select_right _ _ _ _ Cursor_none=Nothing
select_right seq_seq_char typesetting block_number max_row (Cursor_single cursor_press cursor_row cursor_block cursor_char cursor_click)
    |cursor_row==max_row=case error_lookup_sequence "select_right: error 1" max_row seq_seq_char of
        (seq_char,_,char_number,_)->if cursor_char==char_number then Just (max_row,Nothing) else let new_cursor_block=right_select seq_char cursor_block cursor_char in Just (max_row,Just (Cursor_double cursor_press False max_row cursor_block cursor_char cursor_click max_row new_cursor_block (cursor_char+1) new_cursor_block))
    |otherwise=case error_lookup_sequence "select_right: error 2" cursor_row seq_seq_char of
        (seq_char,_,char_number,_)->if cursor_char==char_number then let new_cursor_row=cursor_row+1 in let new_cursor_block=right_select_end seq_seq_char typesetting block_number new_cursor_row in Just (new_cursor_row,Just (Cursor_double cursor_press False cursor_row cursor_block cursor_char cursor_click new_cursor_row new_cursor_block 0 new_cursor_block)) else let new_cursor_block=right_select seq_char cursor_block cursor_char in Just (cursor_row,Just (Cursor_double cursor_press False cursor_row cursor_block cursor_char cursor_click cursor_row new_cursor_block (cursor_char+1) new_cursor_block))
select_right seq_seq_char typesetting block_number max_row (Cursor_double cursor_press cursor_where cursor_row_start cursor_block_start cursor_char_start cursor_click_start cursor_row_end cursor_block_end cursor_char_end cursor_click_end)
    |cursor_where=if cursor_row_start==max_row
        then case error_lookup_sequence "select_right: error 3" max_row seq_seq_char of
            (seq_char,_,_,_)->let new_cursor_char=cursor_char_start+1 in if new_cursor_char==cursor_char_end then Just (max_row,Just (Cursor_single cursor_press max_row cursor_block_end cursor_char_end cursor_click_end)) else let new_cursor_block=right_select seq_char cursor_block_start cursor_char_start in Just (max_row,Just (Cursor_double cursor_press True max_row new_cursor_block new_cursor_char new_cursor_block max_row cursor_block_end cursor_char_end cursor_click_end))
        else case error_lookup_sequence "select_right: error 4" cursor_row_start seq_seq_char of
            (seq_char,_,char_number,_)->if cursor_char_start==char_number then let new_cursor_row=cursor_row_start+1 in if new_cursor_row==cursor_row_end&&cursor_char_end==0 then Just (cursor_row_end,Just (Cursor_single cursor_press cursor_row_end cursor_block_end 0 cursor_click_end)) else let new_cursor_block=right_select_end seq_seq_char typesetting block_number new_cursor_row in Just (new_cursor_row,Just (Cursor_double cursor_press True new_cursor_row new_cursor_block 0 new_cursor_block cursor_row_end cursor_block_end cursor_char_end cursor_click_end)) else let new_cursor_char=cursor_char_start+1 in if cursor_row_end==cursor_row_start&&new_cursor_char==cursor_char_end then Just (cursor_row_end,Just (Cursor_single cursor_press cursor_row_end cursor_block_end cursor_char_end cursor_click_end)) else let new_cursor_block=right_select seq_char cursor_block_start cursor_char_start in Just (cursor_row_start,Just (Cursor_double cursor_press True cursor_row_start new_cursor_block new_cursor_char new_cursor_block cursor_row_end cursor_block_end cursor_char_end cursor_click_end))
    |otherwise=if cursor_row_end==max_row
        then case error_lookup_sequence "select_right: error 5" max_row seq_seq_char of
            (seq_char,_,char_number,_)->if cursor_char_end==char_number then Just (max_row,Nothing) else let new_cursor_block=right_select seq_char cursor_block_end cursor_char_end in Just (max_row,Just (Cursor_double cursor_press False cursor_row_start cursor_block_start cursor_char_start cursor_click_start max_row new_cursor_block (cursor_char_end+1) new_cursor_block))
        else case error_lookup_sequence "select_right: error 6" cursor_row_end seq_seq_char of
            (seq_char,_,char_number,_)->if cursor_char_end==char_number then let new_cursor_row=cursor_row_end+1 in let new_cursor_block=right_select_end seq_seq_char typesetting block_number new_cursor_row in Just (new_cursor_row,Just (Cursor_double cursor_press False cursor_row_start cursor_block_start cursor_char_start cursor_click_start new_cursor_row new_cursor_block 0 new_cursor_block)) else let new_cursor_block=right_select seq_char cursor_block_end cursor_char_end in Just (cursor_row_end,Just (Cursor_double cursor_press False cursor_row_start cursor_block_start cursor_char_start cursor_click_start cursor_row_end new_cursor_block (cursor_char_end+1) new_cursor_block))

click_select::DS.Seq (DS.Seq (Char,Int,FCT.CInt),Int,Int,Bool)->Typesetting->Int->Int->Int->(Int,Int)
click_select seq_seq_char typesetting block_number cursor_row cursor_click=case error_lookup_sequence "click_select: error 1" cursor_row seq_seq_char of
    (seq_char,number,_,_)->from_cursor_click seq_char cursor_click (typesetting_left typesetting number block_number) 0

up_select_start::DS.Seq (DS.Seq (Char,Int,FCT.CInt),Int,Int,Bool)->Typesetting->Int->Int->Int
up_select_start seq_seq_char typesetting block_number cursor_row=case error_lookup_sequence "up_select_start: error 1" cursor_row seq_seq_char of
    (_,number,_,_)->typesetting_left typesetting number block_number

select_up::DS.Seq (DS.Seq (Char,Int,FCT.CInt),Int,Int,Bool)->Typesetting->Int->Cursor->Maybe (Int,Maybe Cursor)
select_up _ _ _ Cursor_none=Nothing
select_up seq_seq_char typesetting block_number (Cursor_single cursor_press cursor_row cursor_block cursor_char cursor_click)
    |cursor_row==0=if cursor_char==0 then Just (0,Nothing) else let new_cursor_block=up_select_start seq_seq_char typesetting block_number 0 in Just (0,Just (Cursor_double cursor_press True 0 new_cursor_block 0 new_cursor_block 0 cursor_block cursor_char cursor_click))
    |otherwise=let new_cursor_row=cursor_row-1 in let (new_cursor_block,new_cursor_char)=click_select seq_seq_char typesetting block_number new_cursor_row cursor_click in Just (new_cursor_row,Just (Cursor_double cursor_press True new_cursor_row new_cursor_block new_cursor_char cursor_click cursor_row cursor_block cursor_char cursor_click))
select_up seq_seq_char typesetting block_number (Cursor_double cursor_press cursor_where cursor_row_start cursor_block_start cursor_char_start cursor_click_start cursor_row_end cursor_block_end cursor_char_end cursor_click_end)
    |cursor_where=if cursor_row_start==0 then if cursor_char_start==0 then Just (0,Nothing) else let new_cursor_block=up_select_start seq_seq_char typesetting block_number 0 in Just (0,Just (Cursor_double cursor_press True 0 new_cursor_block 0 new_cursor_block cursor_row_end cursor_block_end cursor_char_end cursor_click_end)) else let new_cursor_row=cursor_row_start-1 in let (new_cursor_block,new_cursor_char)=click_select seq_seq_char typesetting block_number new_cursor_row cursor_click_start in Just (new_cursor_row,Just (Cursor_double cursor_press True new_cursor_row new_cursor_block new_cursor_char cursor_click_start cursor_row_end cursor_block_end cursor_char_end cursor_click_end))
    |otherwise=if cursor_row_end==0 then if cursor_char_start==0 then Just (0,Just (Cursor_single cursor_press 0 cursor_block_start 0 cursor_click_start)) else let new_cursor_block=up_select_start seq_seq_char typesetting block_number 0 in Just (0,Just (Cursor_double cursor_press True 0 new_cursor_block 0 cursor_click_end 0 cursor_block_start cursor_char_start cursor_click_start)) else let new_cursor_row=cursor_row_end-1 in let (new_cursor_block,new_cursor_char)=click_select seq_seq_char typesetting block_number new_cursor_row cursor_click_end in if new_cursor_row==cursor_row_start&&new_cursor_char==cursor_char_start then Just (cursor_row_start,Just (Cursor_single cursor_press cursor_row_start cursor_block_start cursor_char_start cursor_click_start)) else if (new_cursor_row,new_cursor_char)<(cursor_row_start,cursor_char_start) then Just (new_cursor_row,Just (Cursor_double cursor_press True new_cursor_row new_cursor_block new_cursor_char cursor_click_end cursor_row_start cursor_block_start cursor_char_start cursor_click_start)) else Just (new_cursor_row,Just (Cursor_double cursor_press False cursor_row_start cursor_block_start cursor_char_start cursor_click_start new_cursor_row new_cursor_block new_cursor_char cursor_click_end))

select_down::DS.Seq (DS.Seq (Char,Int,FCT.CInt),Int,Int,Bool)->Typesetting->Int->Int->Cursor->Maybe (Int,Maybe Cursor)
select_down _ _ _ _ Cursor_none=Nothing
select_down seq_seq_char typesetting block_number max_row (Cursor_single cursor_press cursor_row cursor_block cursor_char cursor_click)
    |cursor_row==max_row=case error_lookup_sequence "select_down: error 1" max_row seq_seq_char of
        (_,number,char_number,_)->if cursor_char==char_number then Just (max_row,Nothing) else let new_cursor_block=typesetting_right typesetting number block_number in Just (max_row,Just (Cursor_double cursor_press False max_row cursor_block cursor_char cursor_click max_row new_cursor_block char_number new_cursor_block))
    |otherwise=let new_cursor_row=cursor_row+1 in let (new_cursor_block,new_cursor_char)=click_select seq_seq_char typesetting block_number new_cursor_row cursor_click in Just (new_cursor_row,Just (Cursor_double cursor_press False cursor_row cursor_block cursor_char cursor_click new_cursor_row new_cursor_block new_cursor_char cursor_click))
select_down seq_seq_char typesetting block_number max_row (Cursor_double cursor_press cursor_where cursor_row_start cursor_block_start cursor_char_start cursor_click_start cursor_row_end cursor_block_end cursor_char_end cursor_click_end)
    |cursor_where=if cursor_row_start==max_row
        then case error_lookup_sequence "select_down: error 2" max_row seq_seq_char of
            (_,number,char_number,_)->if cursor_char_end==char_number then Just (max_row,Just (Cursor_single cursor_press max_row cursor_block_end char_number cursor_click_end)) else let new_cursor_block=typesetting_right typesetting number block_number in Just (max_row,Just (Cursor_double cursor_press False max_row cursor_block_end cursor_char_end cursor_click_end max_row new_cursor_block char_number new_cursor_block))
        else let new_cursor_row=cursor_row_start+1 in let (new_cursor_block,new_cursor_char)=click_select seq_seq_char typesetting block_number new_cursor_row cursor_click_start in if new_cursor_row==cursor_row_end&&new_cursor_char==cursor_char_end then Just (cursor_row_end,Just (Cursor_single cursor_press cursor_row_end cursor_block_end cursor_char_end cursor_click_end)) else if (cursor_row_end,cursor_char_end)<(new_cursor_row,new_cursor_char) then Just (new_cursor_row,Just (Cursor_double cursor_press False cursor_row_end cursor_block_end cursor_char_end cursor_click_end new_cursor_row new_cursor_block new_cursor_char cursor_click_start)) else Just (new_cursor_row,Just (Cursor_double cursor_press True new_cursor_row new_cursor_block new_cursor_char cursor_click_start cursor_row_end cursor_block_end cursor_char_end cursor_click_end))
    |otherwise=if cursor_row_end==max_row
        then case error_lookup_sequence "select_down: error 3" max_row seq_seq_char of
            (_,number,char_number,_)->if cursor_char_end==char_number then Just (max_row,Nothing) else let new_cursor_block=typesetting_right typesetting number block_number in Just (max_row,Just (Cursor_double cursor_press False cursor_row_start cursor_block_start cursor_char_start cursor_click_start max_row new_cursor_block char_number new_cursor_block))
        else let new_cursor_row=cursor_row_end+1 in let (new_cursor_block,new_cursor_char)=click_select seq_seq_char typesetting block_number new_cursor_row cursor_click_end in Just (new_cursor_row,Just (Cursor_double cursor_press False cursor_row_start cursor_block_start cursor_char_start cursor_click_start new_cursor_row new_cursor_block new_cursor_char cursor_click_end))

select_swap::Cursor->Maybe (Int,Maybe Cursor)
select_swap Cursor_none=Nothing
select_swap (Cursor_single _ cursor_row _ _ _)=Just (cursor_row,Nothing)
select_swap (Cursor_double cursor_press cursor_where cursor_row_start cursor_block_start cursor_char_start cursor_click_start cursor_row_end cursor_block_end cursor_char_end cursor_click_end)=Just (if cursor_where then cursor_row_end else cursor_row_start,Just (Cursor_double cursor_press (not cursor_where) cursor_row_start cursor_block_start cursor_char_start cursor_click_start cursor_row_end cursor_block_end cursor_char_end cursor_click_end))